name: ESLint Check

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd FrontEnd/air-quality-app
          npm install

      - name: Install ESLint
        run: |
          cd FrontEnd/air-quality-app
          npm install eslint eslint-plugin-react --save-dev

      - name: Run ESLint
        run: |
          cd FrontEnd/air-quality-app
          npx eslint . --ext .js,.jsx